let productsDB = [
    {
      id: 1,
      title: "wooden chair",
      size: "large",
      imageUrl: "images/chair1.jpg",
      overlayImgeUrl: "images/chair6.jpg",
      qty: 1,
      isMe: "N",
    },
    {
      id: 2,
      title: "plastic chair",
      size: "small",
      imageUrl: "images/chair2.jpg",
      overlayImgeUrl: "images/chair5.jpg",
      qty: 1,
      isMe: "N",
    },
    {
      id: 3,
      title: "ionic chair",
      size: "medium",
      imageUrl: "images/chair3.jpg",
      overlayImgeUrl: "images/chair4.jpg",
      qty: 1,
      isMe: "N",
    },
    {
      id: 4,
      title: "moving chair",
      size: "large",
      imageUrl: "images/chair4.jpg",
      overlayImgeUrl: "images/chair3.jpg",
      qty: 1,
      isMe: "N",
    },
    {
      id: 5,
      title: "rest chair",
      size: "medium",
      imageUrl: "images/chair5.jpg",
      overlayImgeUrl: "images/chair2.jpg",
      qty: 1,
      isMe: "N",
    },
    {
      id: 6,
      title: "glasses item",
      size: "large",
      imageUrl: "images/chair6.jpg",
      overlayImgeUrl: "images/chair1.jpg",
      qty: 1,
      isMe: "N",
    },
  ];